In [3]:
# import necessary packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import Ridge

In [5]:
# import csv from prior notebook into new dataframe

data = pd.read_csv('./data/data_4hr.csv')

In [7]:
data = data.set_index('Date')
data.tail()

,Close,Volume,7day_MA,50day_MA,200day_MA,Close_-1,Volume_-1,Close_-2,Volume_-2,Close_-3,...,Close_-20,Volume_-20,Close_-21,Volume_-21,Close_-22,Volume_-22,Close_-23,Volume_-23,Close_-24,Volume_-24
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-28 20:00:00,39501.0,1.7003,35306.261905,34422.016667,44652.707500,39680.0,2.0433,40119.0,3.3157,39732.0,...,34490.0,1.3215,34396.0,0.7262,34017.0,0.9088,33822.0,2.6263,34205.0,1.5605
2021-07-29 00:00:00,39876.0,0.6711,35492.880952,34442.876667,44652.313333,39501.0,1.7003,39680.0,2.0433,40119.0,...,33854.0,1.6524,34490.0,1.3215,34396.0,0.7262,34017.0,0.9088,33822.0,2.6263
2021-07-29 04:00:00,39826.0,1.1360,35683.642857,34467.206667,44651.293333,39876.0,0.6711,39501.0,1.7003,39680.0,...,34388.0,0.3816,33854.0,1.6524,34490.0,1.3215,34396.0,0.7262,34017.0,0.9088
2021-07-29 08:00:00,39992.0,1.7867,35874.738095,34487.856667,44650.821667,39826.0,1.1360,39876.0,0.6711,39501.0,...,34566.0,5.7212,34388.0,0.3816,33854.0,1.6524,34490.0,1.3215,34396.0,0.7262
2021-07-29 12:00:00,40221.0,0.4788,36074.071429,34507.473333,44650.882500,39992.0,1.7867,39826.0,1.1360,39876.0,...,38183.0,6.1060,34566.0,5.7212,34388.0,0.3816,33854.0,1.6524,34490.0,1.3215

In [8]:
data.shape

(6667, 53)

In [15]:
# seperate into train and test, and then X and y

train = data[:6000]
test = data[6000:]

In [16]:
train.shape

(6000, 53)

In [17]:
test.shape

(667, 53)

In [18]:
X_train = train.drop('Close', axis=1)
X_test = test.drop('Close', axis=1)
y_train = train.Close
y_test = test.Close

In [19]:
# initialize the baseline model

baseline = Ridge()

baseline.fit(X_train, y_train)

Ridge()

In [20]:
# predict test variables

y_pred = baseline.predict(X_test)

In [21]:
# evaluate baseline model

baseline_r2 = r2_score(y_test, y_pred)
baseline_MSE = mean_squared_error(y_test, y_pred)

print(f'Baseline model r2: {baseline_r2}\nBaseline MSE: {baseline_MSE}')

Baseline model r2: 0.9934657698847977
Baseline MSE: 691022.6266212492

The baseline model has a very large mean squared error, none of the features have been scaled at this point, will attempt scaling of columns to see if it improves metrics.

In [40]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [41]:
X_train_scaled

array([[-0.64776107, -0.49650743, -0.49742417, ..., -0.64114098,
        -0.486107  , -0.660738  ],
       [-0.6385358 , -0.49583228, -0.49660088, ..., -0.6617898 ,
        -0.51490528, -0.64108   ],
       [-0.66228623, -0.49562548, -0.4963487 , ..., -0.65718467,
        -0.48663072, -0.66172833],
       ...,
       [-0.60661265,  3.86954931,  4.46171048, ..., -0.50394022,
         3.86476787, -0.50840089],
       [-0.60475522,  3.86420681,  4.46336261, ..., -0.52092474,
         3.81433942, -0.50388253],
       [ 0.14205824,  3.86159979,  4.46540603, ..., -0.38690549,
         3.7937288 , -0.52086664]])

In [42]:
X_train_scaled = pd.DataFrame(X_train_scaled, index=X_train.index, columns=X_train.columns)

In [43]:
X_test_scaled = pd.DataFrame(X_test_scaled, index=X_test.index, columns=X_test.columns)

In [44]:
X_train_scaled

,Volume,7day_MA,50day_MA,200day_MA,Close_-1,Volume_-1,Close_-2,Volume_-2,Close_-3,Volume_-3,...,Close_-20,Volume_-20,Close_-21,Volume_-21,Close_-22,Volume_-22,Close_-23,Volume_-23,Close_-24,Volume_-24
Date,,,,,,,,,,,,,,,,,,,,,
2018-07-14 12:00:00,-0.647761,-0.496507,-0.497424,-0.584735,-0.484730,-0.612487,-0.480707,-0.644709,-0.480053,-0.651323,...,-0.489673,-0.649265,-0.487221,-0.657381,-0.486895,-0.661942,-0.515010,-0.641141,-0.486107,-0.660738
2018-07-14 16:00:00,-0.638536,-0.495832,-0.496601,-0.583008,-0.481030,-0.647616,-0.484575,-0.612478,-0.480547,-0.644699,...,-0.487249,-0.646950,-0.489559,-0.649235,-0.487105,-0.657337,-0.486769,-0.661790,-0.514905,-0.641080
2018-07-14 20:00:00,-0.662286,-0.495625,-0.496349,-0.582480,-0.480866,-0.638391,-0.480871,-0.647607,-0.484420,-0.612467,...,-0.520305,-0.642517,-0.487132,-0.646920,-0.489447,-0.649191,-0.486979,-0.657185,-0.486631,-0.661728
2018-07-15 00:00:00,-0.662645,-0.495433,-0.496115,-0.581988,-0.491882,-0.662141,-0.480707,-0.638382,-0.480712,-0.647596,...,-0.487249,-0.652595,-0.520230,-0.642488,-0.487016,-0.646876,-0.489324,-0.649039,-0.486841,-0.657123
2018-07-15 04:00:00,-0.602799,-0.494862,-0.495418,-0.580528,-0.491882,-0.662500,-0.491736,-0.662131,-0.480547,-0.638371,...,-0.487350,-0.662908,-0.487132,-0.652565,-0.520156,-0.642444,-0.486890,-0.646724,-0.489188,-0.648978
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-08 16:00:00,-0.613510,3.874858,4.457919,4.704533,3.634538,-0.543367,3.678797,-0.532078,3.635626,-0.379616,...,3.771886,-0.521142,3.797973,-0.504129,3.853882,-0.508606,3.787933,-0.662681,3.883605,-0.380376
2021-04-08 20:00:00,-0.617423,3.873716,4.460100,4.713004,3.724644,-0.613366,3.639291,-0.543359,3.683581,-0.532068,...,3.782140,-0.387114,3.777439,-0.521114,3.803577,-0.504088,3.859478,-0.508459,3.793138,-0.662620
2021-04-09 00:00:00,-0.606613,3.869549,4.461710,4.721290,3.757693,-0.617279,3.729497,-0.613357,3.644031,-0.543348,...,3.907120,0.145530,3.787706,-0.387088,3.783016,-0.521073,3.809110,-0.503940,3.864768,-0.508401
2021-04-09 04:00:00,-0.604755,3.864207,4.463363,4.729594,3.675480,-0.606469,3.762583,-0.617270,3.734337,-0.613346,...,3.940571,-0.471337,3.912845,0.145550,3.793297,-0.387049,3.788523,-0.520925,3.814339,-0.503883
2021-04-09 08:00:00,0.142058,3.861600,4.465406,4.738055,3.687977,-0.604612,3.680279,-0.606460,3.767460,-0.617259,...,3.939479,-0.528001,3.946339,-0.471309,3.918597,0.145579,3.798817,-0.386905,3.793729,-0.520867

In [45]:
baseline.fit(X_train_scaled, y_train)

Ridge()

In [48]:
y_pred = baseline.predict(X_test_scaled)

In [49]:
# evaluating baseline model with scaled data

baseline_r2_1 = r2_score(y_test, y_pred)
baseline_MSE_1 = mean_squared_error(y_test, y_pred)

print(f'Baseline model r2: {baseline_r2_1}\nBaseline MSE: {baseline_MSE_1}')

Baseline model r2: -7.628007538207443
Baseline MSE: 912448494.5347705

Scaling the data in this case produced a much larger mean squared error and a much worse r2 score also.